backend:
  name: github
  branch: new-layout
  repo: maisahyttinen/lemmikkisotilas

media_folder: static/images
public_folder: /images

collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Yleisasetukset
        file: site-metadata.json
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Seo title / Header title, jota käytetään jos sivulla ei omia tietoja.
          - widget: text
            name: description
            label: Description
            required: true
            hint: Seo description / Header description, jota käytetään jos sivulla ei omia tietoja.
          - widget: list
            name: menuLinks
            label: Menulinks
            fields:
              - widget: string
                name: name
                label: name
              - widget: string
                name: to
                label: To
              - widget: string
                name: variant
                label: Variant (link/button)

          - widget: hidden
            name: none
            label: None
            required: false
            hint: >-
              Just an empty param, allows the site params to be displayed
              properl
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{fields.path}}"
    fields:
      - label: "Template Key"
        name: "template"
        widget: "hidden"
        default: "blog-post"
      - label: Path / Slug / Filename (no äåö characters or spaces e.g. alamoloa-takaapain)
        name: path
        widget: string
        required: true
      - label: SEO Title
        name: header-title
        widget: string
        hint: Näkyy googlessa otsikkona
        required: true
      - label: SEO Description
        name: header-description
        widget: text
        hint: Näkyy googlessa
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
        format: YYYY-MM-DD
        required: true
      - label: "Subtitle"
        name: "subtitle"
        widget: "text"
        hint: Se teksti joka näkyy blogipostauksessa otsikon alapuolla.
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        hint: Se teksti joka näkyy etusivulla blogipostauksen katkelmana.
      - label: "Featured Image"
        name: "img_path"
        widget: "image"
        required: true
        hint: Vain .jpg jookosta kookosta <3
      - label: Spotlights Button label
        widget: string
        name: post_button_label
        default: Lue lisää
        required: false
        hint: The text displayed in the home spotlight button
      - label: "Content"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Generic Pages"
    folder: "src/pages"
    filter: { field: "template", value: "generic-page" }
    create: true
    slug: "{{fields.path}}"
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "generic-page"
      - label: Path / Slug / Filename (no äåö characters or spaces e.g. alamoloa-takaapain)
        name: path
        widget: text
        required: true
      - label: SEO Title
        name: header-title
        widget: string
        required: true
      - label: SEO Description
        name: header-description
        widget: text
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - abel: "Publish Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
        format: YYYY-MM-DD
        required: true
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Featured Image"
        name: "img_path"
        widget: "image"
      - label: "Content"
        name: "body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - label: "Template"
            name: "template"
            widget: "hidden"
            default: "index-page"
          - label: SEO Title
            name: header-title
            widget: string
            required: true
          - label: SEO Description
            name: header-description
            widget: text
            required: true
          - label: Main
            name: main
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Description
                name: description
                widget: text
              - label: Buttons
                name: buttons
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Url
                    name: url
                    widget: string
                    hint: Must be format "/posts/example" or "https://is.fi"

          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: markdown
              - label: Buttons
                name: buttons
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Url
                    name: url
                    widget: string
                    hint: Must be format "/posts/example" or "https://is.fi"
          - label: Spotlight
            name: spotlight
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Footer
                name: footer
                widget: text
              - label: Buttons
                name: buttons
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Url
                    name: url
                    widget: string
                    hint: Must be format "/posts/example" or "https://is.fi"
          - label: Footer
            name: footer
            widget: object
            fields:
              - label: Title
                name: description
                widget: string
              - label: Description
                name: description
                widget: markdown
              - label: Social
                name: social
                widget: list
                fields:
                  - label: Icon
                    name: icon
                    widget: string
                    hint: instagram / facebook / linkedin / gallery
                  - label: Url
                    name: url
                    widget: string
                    hint: Must be format "/posts/example" or "https://is.fi"
